package com.szxb.buspay.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szxb.buspay.db.entity.card.BlackListCard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLACK_LIST_CARD".
*/
public class BlackListCardDao extends AbstractDao<BlackListCard, Long> {

    public static final String TABLENAME = "BLACK_LIST_CARD";

    /**
     * Properties of entity BlackListCard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Card_id = new Property(1, String.class, "card_id", false, "CARD_ID");
        public final static Property Reserve_1 = new Property(2, String.class, "reserve_1", false, "RESERVE_1");
        public final static Property Reserve_2 = new Property(3, String.class, "reserve_2", false, "RESERVE_2");
        public final static Property Reserve_3 = new Property(4, String.class, "reserve_3", false, "RESERVE_3");
        public final static Property Reserve_4 = new Property(5, String.class, "reserve_4", false, "RESERVE_4");
    }


    public BlackListCardDao(DaoConfig config) {
        super(config);
    }
    
    public BlackListCardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLACK_LIST_CARD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARD_ID\" TEXT," + // 1: card_id
                "\"RESERVE_1\" TEXT," + // 2: reserve_1
                "\"RESERVE_2\" TEXT," + // 3: reserve_2
                "\"RESERVE_3\" TEXT," + // 4: reserve_3
                "\"RESERVE_4\" TEXT);"); // 5: reserve_4
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLACK_LIST_CARD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BlackListCard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String card_id = entity.getCard_id();
        if (card_id != null) {
            stmt.bindString(2, card_id);
        }
 
        String reserve_1 = entity.getReserve_1();
        if (reserve_1 != null) {
            stmt.bindString(3, reserve_1);
        }
 
        String reserve_2 = entity.getReserve_2();
        if (reserve_2 != null) {
            stmt.bindString(4, reserve_2);
        }
 
        String reserve_3 = entity.getReserve_3();
        if (reserve_3 != null) {
            stmt.bindString(5, reserve_3);
        }
 
        String reserve_4 = entity.getReserve_4();
        if (reserve_4 != null) {
            stmt.bindString(6, reserve_4);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BlackListCard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String card_id = entity.getCard_id();
        if (card_id != null) {
            stmt.bindString(2, card_id);
        }
 
        String reserve_1 = entity.getReserve_1();
        if (reserve_1 != null) {
            stmt.bindString(3, reserve_1);
        }
 
        String reserve_2 = entity.getReserve_2();
        if (reserve_2 != null) {
            stmt.bindString(4, reserve_2);
        }
 
        String reserve_3 = entity.getReserve_3();
        if (reserve_3 != null) {
            stmt.bindString(5, reserve_3);
        }
 
        String reserve_4 = entity.getReserve_4();
        if (reserve_4 != null) {
            stmt.bindString(6, reserve_4);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BlackListCard readEntity(Cursor cursor, int offset) {
        BlackListCard entity = new BlackListCard( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // card_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // reserve_1
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // reserve_2
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // reserve_3
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // reserve_4
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BlackListCard entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCard_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setReserve_1(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setReserve_2(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setReserve_3(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setReserve_4(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BlackListCard entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BlackListCard entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BlackListCard entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
