package com.szxb.buspay.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szxb.buspay.db.entity.card.LineInfoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LINE_INFO_ENTITY".
*/
public class LineInfoEntityDao extends AbstractDao<LineInfoEntity, Long> {

    public static final String TABLENAME = "LINE_INFO_ENTITY";

    /**
     * Properties of entity LineInfoEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Line = new Property(1, String.class, "line", false, "LINE");
        public final static Property Version = new Property(2, String.class, "version", false, "VERSION");
        public final static Property Up_station = new Property(3, String.class, "up_station", false, "UP_STATION");
        public final static Property Dwon_station = new Property(4, String.class, "dwon_station", false, "DWON_STATION");
        public final static Property Chinese_name = new Property(5, String.class, "chinese_name", false, "CHINESE_NAME");
        public final static Property Is_fixed_price = new Property(6, String.class, "is_fixed_price", false, "IS_FIXED_PRICE");
        public final static Property Is_keyboard = new Property(7, String.class, "is_keyboard", false, "IS_KEYBOARD");
        public final static Property Fixed_price = new Property(8, String.class, "fixed_price", false, "FIXED_PRICE");
        public final static Property Coefficient = new Property(9, String.class, "coefficient", false, "COEFFICIENT");
        public final static Property Shortcut_price = new Property(10, String.class, "shortcut_price", false, "SHORTCUT_PRICE");
        public final static Property FileName = new Property(11, String.class, "fileName", false, "FILE_NAME");
        public final static Property Rmk1 = new Property(12, String.class, "rmk1", false, "RMK1");
        public final static Property Rmk2 = new Property(13, String.class, "rmk2", false, "RMK2");
        public final static Property Rmk3 = new Property(14, String.class, "rmk3", false, "RMK3");
    }


    public LineInfoEntityDao(DaoConfig config) {
        super(config);
    }
    
    public LineInfoEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LINE_INFO_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LINE\" TEXT UNIQUE ," + // 1: line
                "\"VERSION\" TEXT," + // 2: version
                "\"UP_STATION\" TEXT," + // 3: up_station
                "\"DWON_STATION\" TEXT," + // 4: dwon_station
                "\"CHINESE_NAME\" TEXT," + // 5: chinese_name
                "\"IS_FIXED_PRICE\" TEXT," + // 6: is_fixed_price
                "\"IS_KEYBOARD\" TEXT," + // 7: is_keyboard
                "\"FIXED_PRICE\" TEXT," + // 8: fixed_price
                "\"COEFFICIENT\" TEXT," + // 9: coefficient
                "\"SHORTCUT_PRICE\" TEXT," + // 10: shortcut_price
                "\"FILE_NAME\" TEXT," + // 11: fileName
                "\"RMK1\" TEXT," + // 12: rmk1
                "\"RMK2\" TEXT," + // 13: rmk2
                "\"RMK3\" TEXT);"); // 14: rmk3
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LINE_INFO_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LineInfoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(2, line);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(3, version);
        }
 
        String up_station = entity.getUp_station();
        if (up_station != null) {
            stmt.bindString(4, up_station);
        }
 
        String dwon_station = entity.getDwon_station();
        if (dwon_station != null) {
            stmt.bindString(5, dwon_station);
        }
 
        String chinese_name = entity.getChinese_name();
        if (chinese_name != null) {
            stmt.bindString(6, chinese_name);
        }
 
        String is_fixed_price = entity.getIs_fixed_price();
        if (is_fixed_price != null) {
            stmt.bindString(7, is_fixed_price);
        }
 
        String is_keyboard = entity.getIs_keyboard();
        if (is_keyboard != null) {
            stmt.bindString(8, is_keyboard);
        }
 
        String fixed_price = entity.getFixed_price();
        if (fixed_price != null) {
            stmt.bindString(9, fixed_price);
        }
 
        String coefficient = entity.getCoefficient();
        if (coefficient != null) {
            stmt.bindString(10, coefficient);
        }
 
        String shortcut_price = entity.getShortcut_price();
        if (shortcut_price != null) {
            stmt.bindString(11, shortcut_price);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(12, fileName);
        }
 
        String rmk1 = entity.getRmk1();
        if (rmk1 != null) {
            stmt.bindString(13, rmk1);
        }
 
        String rmk2 = entity.getRmk2();
        if (rmk2 != null) {
            stmt.bindString(14, rmk2);
        }
 
        String rmk3 = entity.getRmk3();
        if (rmk3 != null) {
            stmt.bindString(15, rmk3);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LineInfoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(2, line);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(3, version);
        }
 
        String up_station = entity.getUp_station();
        if (up_station != null) {
            stmt.bindString(4, up_station);
        }
 
        String dwon_station = entity.getDwon_station();
        if (dwon_station != null) {
            stmt.bindString(5, dwon_station);
        }
 
        String chinese_name = entity.getChinese_name();
        if (chinese_name != null) {
            stmt.bindString(6, chinese_name);
        }
 
        String is_fixed_price = entity.getIs_fixed_price();
        if (is_fixed_price != null) {
            stmt.bindString(7, is_fixed_price);
        }
 
        String is_keyboard = entity.getIs_keyboard();
        if (is_keyboard != null) {
            stmt.bindString(8, is_keyboard);
        }
 
        String fixed_price = entity.getFixed_price();
        if (fixed_price != null) {
            stmt.bindString(9, fixed_price);
        }
 
        String coefficient = entity.getCoefficient();
        if (coefficient != null) {
            stmt.bindString(10, coefficient);
        }
 
        String shortcut_price = entity.getShortcut_price();
        if (shortcut_price != null) {
            stmt.bindString(11, shortcut_price);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(12, fileName);
        }
 
        String rmk1 = entity.getRmk1();
        if (rmk1 != null) {
            stmt.bindString(13, rmk1);
        }
 
        String rmk2 = entity.getRmk2();
        if (rmk2 != null) {
            stmt.bindString(14, rmk2);
        }
 
        String rmk3 = entity.getRmk3();
        if (rmk3 != null) {
            stmt.bindString(15, rmk3);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LineInfoEntity readEntity(Cursor cursor, int offset) {
        LineInfoEntity entity = new LineInfoEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // line
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // version
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // up_station
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dwon_station
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // chinese_name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // is_fixed_price
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // is_keyboard
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // fixed_price
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // coefficient
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // shortcut_price
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // fileName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // rmk1
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // rmk2
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // rmk3
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LineInfoEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLine(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVersion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUp_station(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDwon_station(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setChinese_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIs_fixed_price(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIs_keyboard(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFixed_price(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCoefficient(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setShortcut_price(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFileName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setRmk1(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRmk2(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setRmk3(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LineInfoEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LineInfoEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LineInfoEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
