package com.szxb.buspay.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szxb.buspay.db.entity.scan.PublicKeyEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PUBLIC_KEY_ENTITY".
*/
public class PublicKeyEntityDao extends AbstractDao<PublicKeyEntity, Long> {

    public static final String TABLENAME = "PUBLIC_KEY_ENTITY";

    /**
     * Properties of entity PublicKeyEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key_id = new Property(1, String.class, "key_id", false, "KEY_ID");
        public final static Property Pubkey = new Property(2, String.class, "pubkey", false, "PUBKEY");
        public final static Property Remark_1 = new Property(3, String.class, "remark_1", false, "REMARK_1");
        public final static Property Remark_2 = new Property(4, String.class, "remark_2", false, "REMARK_2");
    }


    public PublicKeyEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PublicKeyEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PUBLIC_KEY_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"KEY_ID\" TEXT UNIQUE ," + // 1: key_id
                "\"PUBKEY\" TEXT UNIQUE ," + // 2: pubkey
                "\"REMARK_1\" TEXT," + // 3: remark_1
                "\"REMARK_2\" TEXT);"); // 4: remark_2
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PUBLIC_KEY_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PublicKeyEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String key_id = entity.getKey_id();
        if (key_id != null) {
            stmt.bindString(2, key_id);
        }
 
        String pubkey = entity.getPubkey();
        if (pubkey != null) {
            stmt.bindString(3, pubkey);
        }
 
        String remark_1 = entity.getRemark_1();
        if (remark_1 != null) {
            stmt.bindString(4, remark_1);
        }
 
        String remark_2 = entity.getRemark_2();
        if (remark_2 != null) {
            stmt.bindString(5, remark_2);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PublicKeyEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String key_id = entity.getKey_id();
        if (key_id != null) {
            stmt.bindString(2, key_id);
        }
 
        String pubkey = entity.getPubkey();
        if (pubkey != null) {
            stmt.bindString(3, pubkey);
        }
 
        String remark_1 = entity.getRemark_1();
        if (remark_1 != null) {
            stmt.bindString(4, remark_1);
        }
 
        String remark_2 = entity.getRemark_2();
        if (remark_2 != null) {
            stmt.bindString(5, remark_2);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PublicKeyEntity readEntity(Cursor cursor, int offset) {
        PublicKeyEntity entity = new PublicKeyEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // key_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pubkey
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // remark_1
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // remark_2
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PublicKeyEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPubkey(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRemark_1(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemark_2(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PublicKeyEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PublicKeyEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PublicKeyEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
